name: Deploy a Demoday

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Instalar dependencias
        run: npm install

      - name: Generar Build (Vite)
        run: npm run build

      - name: Desplegar vía FTP a Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.1.0
        with:
          server: ftp://77.37.93.92
          username: ${{ secrets.FTP_USERNAME }}   # Asegúrate de definir este secret en GitHub
          password: ${{ secrets.FTP_PASSWORD }}   # Asegúrate de definir este secret en GitHub
          local-dir: dist
          server-dir: /public_html/demoday
